### ISSUE TITLE
any type of drill reports no ground contract despite the drill touches perfectly

### ISSUE THREAD

**Issue by tonimark** [steamp0rt/Kerbalism#102]
the drill doesn't work even if he touches the ground
![20180703201355_1](https://user-images.githubusercontent.com/17166550/42234659-ebc276ba-7efd-11e8-941d-bce1cc153518.jpg)

**Comment by PiezPiedPy** [comment]
Because you are on the runway.

![screenshot0](https://user-images.githubusercontent.com/17555434/42236553-209aa66a-7ef3-11e8-8fc9-66796f4d662f.png)

**Comment by tonimark** [comment]
oh k thanks

**Comment by tonimark** [comment]
how to close the issue

**Comment by PiezPiedPy** [comment]
should be a close button next to comment buttonn
