### ISSUE TITLE
SOLAR PANES DOESN'T GIVE ANY ELECTICITY

### ISSUE THREAD

**Issue by tonimark** [steamp0rt/Kerbalism#121]
no power output of my solar panels it doesn't even say "broken" in status 
![20180709163025_1](https://user-images.githubusercontent.com/17166550/42454081-43398bc0-8397-11e8-94b3-ded27d6efe34.jpg)

**Comment by PiezPiedPy** [comment]
@tonimark No need to shout 😛 
What mod are the solar panels associated with ?, maybe support is not added for the mod

**Comment by eberkain** [comment]
Those are from feline utility rovers, the companion to planetary base systems.  I have had no problem using them in 1.4.5 so its probably safe to close this.
