### ISSUE TITLE
battery notificator say @kerbalism_... instead of normal words

### ISSUE THREAD

**Issue by tonimark** [steamp0rt/Kerbalism#122]
something is broken here plz fix that
![20180709164733_1](https://user-images.githubusercontent.com/17166550/42454316-dcd7ac30-8397-11e8-9c15-bdead29eadfc.jpg)
![20180709164629_1](https://user-images.githubusercontent.com/17166550/42454323-e33cf184-8397-11e8-90ac-a2918a257637.jpg)
![20180709164656_1](https://user-images.githubusercontent.com/17166550/42454328-e6f77736-8397-11e8-8a6a-05291f7cb1d3.jpg)

**Comment by tonimark** [comment]
look the black box at the middle

**Comment by MartinDomig** [comment]
This was fixed #105 and will be in the next released version.

**Comment by Gordon-Dry** [comment]
I just wanted to say:
Try https://github.com/steamp0rt/Kerbalism

**Comment by PiezPiedPy** [comment]
needs closing
