### ISSUE TITLE
Data lost when attach things with KAS

### ISSUE THREAD

**Issue by Toranks** [steamp0rt/Kerbalism#147]
All of data are lost if I attach anything with KAS / KIS and an engineer. Apparently if attached to a part attached with a connector port at least one jump from where the data is

![kerbal 2](https://user-images.githubusercontent.com/40789364/42917160-af8962fa-8b08-11e8-9445-ef19a9ad3bce.jpg)
![kerbal 1](https://user-images.githubusercontent.com/40789364/42917208-ee8e159a-8b08-11e8-9b3a-d61a4ec7e11d.jpg)

**Comment by Toranks** [comment]
It seems not related to conector port. It also happens even if there is no port connected. Just by connecting something with KAS

![image](https://user-images.githubusercontent.com/40789364/42917595-79ed1a2c-8b0a-11e8-89c6-4194bfe2fe88.png)

**Comment by Toranks** [comment]
I started a game just to reproduce the problem
[KSP.log](https://github.com/steamp0rt/Kerbalism/files/2210732/KSP.log)

**Comment by steamp0rt** [comment]
Ok, thanks. It doesn't appear to be an error.

**Comment by SirMortimer** [comment]
This should be fixed in 3.0

**Comment by steamp0rt** [comment]
fixed in 3.0
