### ISSUE TITLE
Device list usability

### ISSUE THREAD

**Issue by MartinDomig** [steamp0rt/Kerbalism#156]
With large stations or bases, the device list quickly grows beyond anything remotely usable.

Ideas:
* sort devices by name
* put them in a tree view, categorized by type (life support, chemical processors, electrical, lights, antennas, ...)
* maybe include a text filter (type in "waste" to quickly find out if your waste processors are running)

<img width="812" alt="bildschirmfoto 2018-07-22 um 13 52 55" src="https://user-images.githubusercontent.com/4105874/43045310-abdcc902-8db6-11e8-8208-7e6901600bbb.png">

**Comment by Gordon-Dry** [comment]
Yeah, makes sense.
