### ISSUE TITLE
SSPX IVAs not rotating

### ISSUE THREAD

**Issue by theJesuit** [steamp0rt/Kerbalism#158]
The IVAs of the SSPX centrifuges don't rotate.

Kerbalism removes the SSPX proprietary Part Module that handles rotating of both part AND its Internal.  Kerbalism then uses its own Part module based on habitat and pressure but this doesn't appear to be ties to the Internals.

Could the IVAs be made to rotate in time to the part please?

Peace.

**Comment by HaullyGames** [comment]
Hi @theJesuit,

I've to confirm it's still my version of it.
I worked on this 6 months ago, I remember that I was lazy in this module and left the internal view without rotation.

Please let me know if this problem is still happening.

I'm trying to get back to Kerbalism.

**Comment by PiezPiedPy** [comment]
@HaullyGames probably is because no one has fixed it yet
