### ISSUE TITLE
Desactivate message by default and pause when there is one

### ISSUE THREAD

**Issue by SylvainLasnier** [steamp0rt/Kerbalism#185]
Hi,
Due to Kerbalism rules, most of vessel are unmanned probe and alert message dont matter a lot for them. And with lot of probe, it become confuse.
In another hand alert messages are vital for manned station. But it is easy to miss some critical message when your are wrapping to the next maneuver.

So, is it possible to desactivate message by default in the cfg panel?
Is it possible to pause the game when a message is display? (option like alarm clock)
Nice to have, is it possible switch to the vessel by clicking on this list?

br

**Comment by eberkain** [comment]
I think I'm following you so I can try to answer.  

> So, is it possible to desactivate message by default in the cfg panel?
You can deactivate messages on a per vessel basis, but they are all on by default.  I'm not sure there is alot of value in being able to configure this before hand.  You could have it inherit when a vessel is undocked/decoupled, but that could lead to situations where a message is disabled that you did not intend to have disabled which might kill your crew without letting you know there was a problem.  Its probably safer to always have them on by default and toggle on a per vessel basis in-flight.  

> Is it possible to pause the game when a message is display? (option like alarm clock)
A message will break out of warp currently, but this has a conflict with some auto-warping mods like MechJeb which immediately starts warping again.  This may be something that could be looked at, but probably belongs in a separate issue with clear details. 

> Nice to have, is it possible switch to the vessel by clicking on this list?
That could be a good feature to add to the vessel list, also the ability to target any vessel anywhere off the list would be handy.  Not sure how the UI would be implemented though, that list is already jam packed with icons and text.

**Comment by PiezPiedPy** [comment]
switching vessel by clicking on the list in the panel might be problematic as that is how a vessel is selected for viewing its details and using right click is just as bad because that is used to hide the panel.

An option in the cfg panel to pause the game on a message might be possible.

**Comment by eberkain** [comment]
The option to sort the list A-Z or Z-A or default would be nice.  :)  

Vessel switching and vessel targeting would both take new buttons i think, maybe you could squeeze them onto the bottom tab list with info, data, auto, etc...

**Comment by SirMortimer** [comment]
> switching vessel by clicking on the list in the panel might be problematic

mabe do it with a button in the vessel details?

**Comment by SylvainLasnier** [comment]
It make sense

**Comment by SylvainLasnier** [comment]
> I think I'm following you so I can try to answer.
> 
> > So, is it possible to desactivate message by default in the cfg panel?
> 
> You can deactivate messages on a per vessel basis, but they are all on by default. I'm not sure there is alot of value in being able to configure this before hand. 

Default activation is not a problem when you manage around 10 vessels. 
But when you launch 30 and more probes, space stations, bases to colonize Kerbal system and execute some contracts, this is unusable. AMHO
