### ISSUE TITLE
Add Vessel Type Filters to Vessel List

### ISSUE THREAD

**Issue by eberkain** [steamp0rt/Kerbalism#186]
The vessel list can become quite cluttered, the groups feature is nice but a simpler filter would be greatly appreciated.  I picture it just using the same vessel designations and icons from map view/tracking station.  It would just be a row of icons that you could toggle on and off each one to have those types of vessels show up in the vessel list, so If I wanted to see all my bases, landers and spacecraft I could just toggle those on while leaving off the relays and probes.

**Comment by MartinDomig** [comment]
<img width="476" alt="bildschirmfoto 2018-09-02 um 20 54 12" src="https://user-images.githubusercontent.com/4105874/44959692-dbef1e80-aef2-11e8-93a0-22464937bf24.png">
<img width="467" alt="bildschirmfoto 2018-09-02 um 20 54 50" src="https://user-images.githubusercontent.com/4105874/44959694-de517880-aef2-11e8-9594-b653258ad62c.png">

**Comment by eberkain** [comment]
Ohh that looks nice

**Comment by lordcirth** [comment]
As it has been merged, should this issue be closed?  Also nice work!
