### ISSUE TITLE
Bug: Fuel cells dump setting not saved

### ISSUE THREAD

**Issue by clintonmead** [steamp0rt/Kerbalism#189]
Using build from the 30th of August it looks like the fuel cell dump setting is not saved if it's changed in flight, once you switch away from the ship (say back the the space center) the dump setting is set back to nothing.

Please reply if you need any more details.

**Comment by PiezPiedPy** [comment]
It's a known issue, the feature was only added a few days ago and has not been released yet, it also happens with the chemical processes dump valves, thanks anyway 😉

**Comment by clintonmead** [comment]
Cheers I thought that would be the case thanks for the quick reply also.

I'll make sure I get it right in the vehicle assembly for the moment.

Great mod by the way really enjoy it.

**Comment by SirMortimer** [comment]
Isn't this fixed with #202, @PiezPiedPy?

**Comment by PiezPiedPy** [comment]
Yep
