### ISSUE TITLE
Mechjeb Support

### ISSUE THREAD

**Issue by eberkain** [steamp0rt/Kerbalism#197]
One of the annoying things I have run across while using Mechjeb + Kerbalism is the warping functionality.  

Lets say Mechjeb is in the "execute next maneuver node" mode, and that node is days away in time.  Then MJ will automatically try to warp to the node, ive seen it go to maximum warp if the node is quite far away.  

If during that auto-warping Kerbalism sends out a system message about something important that you need to look at (crew suffocating, etc..) it will kill the timewarp and put it back to 1x.  But MJ is still in its execute mode and immediately starts raising the warp level to finish auto warping to the next node.  

When MJ has control of the vessel there is a button in the interface windows that is called "Abort node execution", pressing that button kills MJ control and stops it from auto warping.  I don't know enough about how unity works, but is it possible for Kerbalism to automatically call the MJ function equivalent of pressing that abort button whenever a system message is sent out that should stop warp?

**Comment by PiezPiedPy** [comment]
If MechJeb has an API with a method to call for the abort button then it should not be a problem to implement, otherwise we could try reflection but it would probably better to add the API method to MechJeb if it does not exist.

**Comment by eberkain** [comment]
I know kRPC has a plugin for MJ that allows you to control MJ by sending commands to kRPC, so there may already be an API in some form, i'm not familiar enough with how all that works to really know though.

**Comment by SirMortimer** [comment]
Doesn't look like there's an API to me. Others have the same problem, like KAC. See https://github.com/MuMech/MechJeb2/issues/1019

**Comment by eberkain** [comment]
It may be worth looking at how RPM handles MJ.  I know you can use it to control everything in IVA.  https://github.com/Mihara/RasterPropMonitor/tree/master/MechJebRPM

**Comment by steamp0rt** [comment]
unfixable without api
