### ISSUE TITLE
Use Courage, Stupidity and Veteran crew status

### ISSUE THREAD

**Issue by SylvainLasnier** [steamp0rt/Kerbalism#198]
Could we use courage, stupidity, level and veteran crew status to alter the gameplay?
For example:   
* a stupid engineer is less able to repair a failure
* a stupid scientist could loose data to analyse in Lab
* a stupid pilot could fail to maneuver ship
* a brave crew accept more radiation, poisoning and other kerbalism miseries...
* a veteran could detect some issue without sensor
...
TBD

**Comment by SirMortimer** [comment]
I'm currently tinkering with using courage+stupidity to affect process rates on an individual basis. The effect would be that two kerbals on the same vessel would each use slightly different amounts of food, water and oxygen, for instance. Note that Kerbalism already has things that depend on individual Kerbals, like the time it takes to die from starvation or from radiation poisoning.

I wouldn't know if having stupid scientists loose data in the lab wouldn't take it too far, but repairs already require Engineers with a minimal level, depending on the component that needs to be repaired. 

What will be worth looking into is having the crew levels affect the efficiency of a lab or a drill, like stock KSP does it. A level 5 scientist processes data quicker, a level 5 engineer helps a harvest drill to operate more efficiently.

**Comment by HaullyGames** [comment]
I think is a good idea.
The KerbalBreakdown already create a random loose data event when vessel has data.
Also, why don't use stupidity to affect the KerbalBreakdown system? using it as a multiple to occur KerbalBreakdown.wrong_valve in Breakdown method?
The Misc.Breakdown method receive ProtoCrewMember c, but it is doing nothing with that.

**Comment by SirMortimer** [comment]
I'm intrigued :)

How about this: let's assume kerbals aren't perfect, and can make mistakes when under stress. Stress is almost zero early in a mission, but as they stay in space for a very long time, their stress level rise - as does the likelihood for them making a mistake (a breakdown). That likelihood can be affected by a kerbals individual stupidity, more stupid -> more errors. Now, if the Kerbal really DOES make a mistake, that in turn raises his stress level...

This, in combination with a setting to turn off such stress induced breakdowns and maybe a slider to  tweak the probability of an error happening once per week or so.

**Comment by SirMortimer** [comment]
I guess when #203 and #204 are merged, this can be closed.

**Comment by SirMortimer** [comment]
@steamp0rt this can be closed.
