### ISSUE TITLE
Kerbalism installed but some features missing.

### ISSUE THREAD

**Issue by HypeWolf** [steamp0rt/Kerbalism#206]
Title.
Things such as resources are needed, therefore they're actually working. However, things like the Kerbalism app button are missing and the menus for "Configure [x]" appear to not do anything.
Reinstalled the mod several times clean installs of the game.
Maybe I'm missing something, but I really don't know what it could be.

**Comment by leomike** [comment]
@HypeWolf 
What version of KSP/Kerbalism?
Did you use CKAN or downloaded from the forum/GitHub?
Did you install dependencies (Module Manager and Community Resource Pack)?

**Comment by theJesuit** [comment]
Also contract configurator

**Comment by HypeWolf** [comment]
Game v1.4.9, using Kerbalism v1.9.0.0.
Tried from every download available and still got the same problem.
And yes, I installed the dependencies too.
Had Contract Configurator in some of the clean installs. Was testing If some mod was causing the problem but seems like it is not the case.

**Comment by PiezPiedPy** [comment]
KerboKatz FrameLimiter mod is known to make the Icons disappear.
Can you post a screenshot of your GameData folder and the Kerbalism folder, will help in diagnosing

**Comment by HypeWolf** [comment]
I got 3 "GameData". I know I can use GameDataSwitcher but I usually have 2 KSPs running at the same time.

Heavily Modded GameData
![image](https://user-images.githubusercontent.com/26725549/45819563-3ede0500-bcaa-11e8-8956-0debd26ffdf1.png)
Modded GameData
![image](https://user-images.githubusercontent.com/26725549/45819584-50bfa800-bcaa-11e8-948f-8ca9f1d66abf.png)
"Vanilla" GameData
![image](https://user-images.githubusercontent.com/26725549/45819588-52896b80-bcaa-11e8-992e-3a546ef17191.png)

**Comment by PiezPiedPy** [comment]
There is your problem, The GameData folder is not root of your install

**Comment by HypeWolf** [comment]
All of the root directories look exactly like this.
Only GameData (and saves, for obvious reasons) are different.
![image](https://user-images.githubusercontent.com/26725549/45820725-0f7cc780-bcad-11e8-914b-201cbf9dfcf4.png)

**Comment by PiezPiedPy** [comment]
hmmm should be ok then, only problem I can see is your Vanilla GameData does not have Kerbalism's dependencies.
Did you delete your Kerbalism folders before installing the latest release ? Some files where moved which will cause problems if you don't delete the folder before install.

**Comment by HypeWolf** [comment]
Yes, I actually did. I edited the comment not so long ago.

**Comment by HypeWolf** [comment]
Yep. Same problem. Tried both, installing manually and using CKAN.

**Comment by PiezPiedPy** [comment]
can you post your KSP.log

**Comment by HypeWolf** [comment]
Was working on something. There you go.
[KSP.log](https://github.com/steamp0rt/Kerbalism/files/2401903/KSP.log)

**Comment by PiezPiedPy** [comment]
Unity have moved the method that is used for loading the icons. Fix will be in the next release, until then here is a v1.9.1 dev build
[Kerbalism-v1.9.1_For_KSP1.4.5.zip](https://github.com/steamp0rt/Kerbalism/files/2402580/Kerbalism-v1.9.1_For_KSP1.4.5.zip)
