### ISSUE TITLE
Connected State not Updated in Background

### ISSUE THREAD

**Issue by leomike** [steamp0rt/Kerbalism#212]
Using stock CommNet, the connected/unconnected status of unloaded vessels is innacurate. There seems to be two separate issues:
1. Unloaded vessels keep their current signal status until a scene change or until the vessel is selected/highlighted in the tracking station, this issue happens at the KSC, tracking station, and when a different vessel is loaded
2. Vessels without a connection will gain one (according to Kerbalism) if they are unloaded by going directly to the tracking station

This does not impact vessels that are loaded in the foreground, nor does it impact the CommNet lines drawn by KSP.

This issue could be related to #133.

Kerbalism 1.9.1 build 135 & dependencies only
KSP 1.4.5 x64 on Windows

**Comment by HaullyGames** [comment]
I knew this bug before test.
I said that in Discord

> Haully
>  09/11/2018
> yep, but ControlPath for CommNet is not updated for unloaded vessel (until I remember)

This is CommNet behavior, has a way to force CommNet update all ControlPath every NetworkUpdate(), but as I remember, it was have for the game.
I will review it when I finish my Habitat changes.

**Comment by PiezPiedPy** [comment]
This is due to CommNet, it's an issue I could not resolve 😞

**Comment by PiezPiedPy** [comment]
One thing I have noticed is this bug only seems to happen if you change scenes with the Pause(ESC) Menu 🤷‍♂️

**Comment by HaullyGames** [comment]
I will confirm @PiezPiedPy , but I remember it wasn't related to Pause game, but in CommNet has a method call NetworkUpdate() that has filters for only loaded vessels. I will find it try reverse engineer.
What I did in my personal version was: Create a class children class from that one, then in my I simple change the filter to all.
I have to check, it was almost a year ago

**Comment by PiezPiedPy** [comment]
Can the original class filter field be changed with Reflection ?
