### ISSUE TITLE
RemoteTech: no connection - Kerbalism throws exceptions

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#221]
```
NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.ConnectionInfo..ctor (.Vessel v, Boolean powered, Boolean storm) [0x00000] in <filename unknown>:0 
  at KERBALISM.Vessel_info..ctor (.Vessel v, UInt32 vessel_id, UInt64 inc) [0x00000] in <filename unknown>:0 
  at KERBALISM.Cache.VesselInfo (.Vessel v) [0x00000] in <filename unknown>:0 
  at KERBALISM.Kerbalism.FixedUpdate () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
```

btw there were several schedules commands in the RT flight computer ...

Using the latest master valid as of time of posting.

**Comment by Gordon-Dry** [comment]
I'll post the full log, one moment...

**Comment by Gordon-Dry** [comment]
https://www.dropbox.com/s/zce0yqfedsp128s/2018-10-07_1%20KSP.log%20and%20stuff.7z?dl=1

**Comment by leomike** [comment]
@Gordon-Dry Did you try a clean install with only Kerbalism and its dependencies (Community Resource Pack, Contract Configurator, Module Manager).

**Comment by Gordon-Dry** [comment]
GameData:

CommunityResourcePack\
ContractConfigurator\
Kerbalism\
Squad\
ModuleManager.3.0.7.dll

Log excerpt:
```
NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Highlighter.Update () [0x00000] in <filename unknown>:0 
  at KERBALISM.Kerbalism.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Kerbalism.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Kerbalism.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

```

^spam - as reached the SPC

**Comment by Gordon-Dry** [comment]
It begins like this:
```
[UIApp] OnDestroy: Missions App
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Kerbalism.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Kerbalism.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Highlighter.Update () [0x00000] in <filename unknown>:0 
  at KERBALISM.Kerbalism.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

[MessageSystem] Reposition 0.02 3475
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[GenericAppFrame] Reposition 0.02 3475
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[GenericAppFrame] Reposition 0.02 3475
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Kerbalism.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Kerbalism.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Highlighter.Update () [0x00000] in <filename unknown>:0 
  at KERBALISM.Kerbalism.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Kerbalism.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Kerbalism.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Highlighter.Update () [0x00000] in <filename unknown>:0 
  at KERBALISM.Kerbalism.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Kerbalism.OnGUI () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

```

etc. pp.

**Comment by Gordon-Dry** [comment]
Same happens when starting a brand new career with only the mods above ...

**Comment by steamp0rt** [comment]
Not getting it on latest master w/ RemoteTech

**Comment by Gordon-Dry** [comment]
This is so weird, now I reverted to latest release from September 15 and my normal modded game - and also have this issue ...

Does not make any sense.

Miraculous.

It started two days ago with that master repo ...

**Comment by Gordon-Dry** [comment]
I will try now with latest master (not bootstrapped yet?), minimum mods and without game start parameters ...

**Comment by steamp0rt** [comment]
Sent probe to space, probe lost connection. Went to space center, probe, and tracking station. Error did not show up in logs.

Master will be bootstrapped when I get Travis up and running

**Comment by Gordon-Dry** [comment]
Puh, now it works.
I started a new career to be sure.

Another test with my usual -force-glcore parameter will follow ...

**Comment by Gordon-Dry** [comment]
Still works.
Now I add RemoteTech.
And then I will cheat a probe into orbit and check it again ...

**Comment by steamp0rt** [comment]
I don't think graphics settings will affect non-graphics errors

**Comment by Gordon-Dry** [comment]
Still okay in SPC.
Okay in VAB.

I built a probe with a deployed antenna, cheated it into orbit, disabled the antenna.
No issue.
Tracking Station no issue.
SPC no issue.

Now I could either try it again with the full pack - or just with the necessary mods for RSS.
Yeah, I will do that first.

**Comment by Gordon-Dry** [comment]
Still not an issue.

I will test with my full install now as it was before (and worked until two days ago without Kerbalism spam)...

**Comment by Gordon-Dry** [comment]
So, this time it's different....

But still an issue. I must be another mod - but WHY did I also have this (kinda) issue with a minimum install?

- The icon is there (in SPC)
- But no vessels are listed (two in orbit, unmanned)

Spam:
```
NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.ConnectionInfo..ctor (.Vessel v, Boolean powered, Boolean storm) [0x00000] in <filename unknown>:0 
  at KERBALISM.Vessel_info..ctor (.Vessel v, UInt32 vessel_id, UInt64 inc) [0x00000] in <filename unknown>:0 
  at KERBALISM.Cache.VesselInfo (.Vessel v) [0x00000] in <filename unknown>:0 
  at KERBALISM.Monitor.Render_vessel (KERBALISM.Panel p, .Vessel v, Boolean selected) [0x00000] in <filename unknown>:0 
  at KERBALISM.Monitor.Update () [0x00000] in <filename unknown>:0 
  at KERBALISM.Launcher.Update () [0x00000] in <filename unknown>:0 
  at KERBALISM.UI.Update (Boolean show_window) [0x00000] in <filename unknown>:0 
  at KERBALISM.Kerbalism.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.ConnectionInfo..ctor (.Vessel v, Boolean powered, Boolean storm) [0x00000] in <filename unknown>:0 
  at KERBALISM.Vessel_info..ctor (.Vessel v, UInt32 vessel_id, UInt64 inc) [0x00000] in <filename unknown>:0 
  at KERBALISM.Cache.VesselInfo (.Vessel v) [0x00000] in <filename unknown>:0 
  at KERBALISM.Kerbalism.FixedUpdate () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

```

First appearance:
```
10/8/2018 2:34:51 AM,TransferWindowPlanner,Successfully Hooked the KAC
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.ConnectionInfo..ctor (.Vessel v, Boolean powered, Boolean storm) [0x00000] in <filename unknown>:0 
  at KERBALISM.Vessel_info..ctor (.Vessel v, UInt32 vessel_id, UInt64 inc) [0x00000] in <filename unknown>:0 
  at KERBALISM.Cache.VesselInfo (.Vessel v) [0x00000] in <filename unknown>:0 
  at KERBALISM.Kerbalism.FixedUpdate () [0x00000] in <filename unknown>:0 

```

This time the icon exists in VAB ...
No log spamming here.

Loaded a craft, still okay.

Build it with KCT, back to SPC: spam ...

Let it build...

Launchpad:
Icons exists this time, only shows the actual vessel in focus, same spam.

**Comment by Gordon-Dry** [comment]
Full log and stuff:
https://www.dropbox.com/s/91asrxaxpxo83b2/2018-10-08_1%20KSP.log%20and%20stuff.7z?dl=1

**Comment by steamp0rt** [comment]
@HaullyGames @leomike

**Comment by Gordon-Dry** [comment]
How about that:

If the minimum install also triggered that kind of issue, could it be ContractConfigurator or even the CommonResources somehow?

**Comment by leomike** [comment]
> Still not an issue.
> 
> I will test with my full install now as it was before (and worked until two days ago without Kerbalism spam)...
I thought the minimal install didn't throw any exception error or cause any issues. Can you confirm at what point in your testing the error showed up?

**Comment by Gordon-Dry** [comment]
Well, I just launch the vessel now - fun fact:
I cannot zoom with the mouse wheel.

I did the input lock thing, but that didn't help.

**Comment by Gordon-Dry** [comment]
Issue gone after removing:

KSP-IE, or any of

InterstellarHybridRocketry\
WarpPlugin\
TweakScale\
PhotonSail\
SolarSailNavigator\

because I removed those mods / folders.

**Comment by Gordon-Dry** [comment]
But, still i wonder why the bare minimum install also threw those issues with a new career...

Some magic memory reminders because of page swapping?

**Comment by Gordon-Dry** [comment]
So, it was "solved" somehow, also as a reminder to @leomike @sswelm:

@HaullyGames did some tests with a copy of my GameData folder and my saves subfolder in debug mode.
Correct me if I'm wrong in reproducing what you did.

There was a vessel in my game which, after adding KSP-IE, had no more EC as a resource in the persistent file.
This error triggered the Kerbalism exceptions.
```
    else
                                        {
                                            Lib.Debug("packet_size != null");
                                            rate += ((float)packet_size / Lib.ReflectionValue<float>(pm, "RTPacketInterval")) * PreferencesBasic.Instance.transmitFactor;
                                            external_cost += pm.resHandler.inputResources.Find(r => r.name == "ElectricCharge").rate;
                                        }
```
```
// return no connection if there is no ec left
            if (!powered)
            {
                Lib.Debug("Vessel '{0}' has no Power",v.vesselName);
```
After removing KSP-IE the error was still there, because the resource EC was missing in that particular vessel in the persistent file, but loading that vessel immediately repaired it and solved that issue.

It's quirky, and not 100% clear to say what the real culprit was, but it appeared after adding KPS-IE and was gone after removing KPS-IE (immediately, without the need of loading that partivcular vessel first).

But it seems that there also is something not 100% failsafe in Kerbalism's code.

So both mods need some revision.

**Comment by sswelm** [comment]
An often made mistake is to assume resource variable stay persistant once loaded, but that is not the case as they can be removed or replaced by other mods

**Comment by Gordon-Dry** [comment]
It could be that RealBattery has to do with it - a part that is patched to be RealBattery compatible has the Resource ElectricCharge just renamed to StoredCharge, the plugin itself provides the ElectricCharge to the part somehow.

As long as it's only a battery it's not a problem, but if a small probe is patched to be RealBattery compatible there is no more ElectricCharge in the part as resource, but StoredCharge instead.

**Comment by Gordon-Dry** [comment]
Ah, okay.
Inside the MM cache is only SC, but inside the persistent file there also is EC - created by the RealBattery plugin.
Perhaps KSP-IE hindered RealBattery in doing this ...

**Comment by sswelm** [comment]
KSP-IE doesn't touch ElectricCharge unless it contains IFS/KSPIE part modules.

**Comment by steamp0rt** [comment]
...

**Comment by HaullyGames** [comment]
I didn't get it.

**Comment by Gordon-Dry** [comment]
Well, whatever, scrap that.

KAC created severe issues, whose manifested in the low fps in Tracking Station.
Then the persistant file of my last career which I had to scrap 2 days ago had some vessels just missing EC (yeah, RealBattery replaces EC with SC and does the EC part by plugin)...
I never had issues of this kind because of RealBattery alone.
Then the NaN kraken fucked up the orbits of two early probes.

I will close this for now - until the next round.
