### ISSUE TITLE
Suggestion: Show remaining transmission time when hovering over file manager data set

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#234]
As soon as a connection is established the remaining time to transmit the actual data set entry in the file manager should be shown in the tooltip as well.

**Comment by HaullyGames** [comment]
I really like this ideas.
Working on it.

**Comment by HaullyGames** [comment]
Can be close.
https://github.com/steamp0rt/Kerbalism/pull/246

**Comment by Gordon-Dry** [comment]
Yep
