### ISSUE TITLE
Suggestion: get antennasurface by model and calculate a RL-ish transfer bitrate

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#244]
CommNet and RT

By code, get the textured surface of an antenna.
Check, if it's a direct/omni or relay/dish
    direct/omni derive the length when deployed
    relay/dish derive the surface of the dish (the active side ofc)
Get the mass.

Use some predefined table values derived from RL antennas which in prototype testing resulted in bitrate values that fit the RL counterpart of that antenna part.
(Old antennas used analog data, but da fuq then compare with newer antennas of similar size/shape.)

Use the table values, the lenght/surface and the mass to calculate a transfer bitrate which is somehow realistic.
Ignore the config/patch values which are usually used to calculate the bitrate.

Make the whole thing optional by Kerbalism setting.
(so default is "normal" behaviour)

---

Discord excerpt:
```
Gordon Dry
What goofs me is the bitrate of many antennas - early tech tree antennas are mostly too fast imho

Haully
Antenna realistic is not with me
I don't know nothing about antennas

Gordon Dry
I try to fiddle a generic patch that uses the antenna's mass to calculate a lower value ...

Haully
ask PiezPiedPy , looks like he works with it or a least knows more than me(bearbeitet)
We can try to use antennas mass or antennas size
in code we can get the texture area

Gordon Dry
That patch includes probe cores when they have RTAntenna (not passive), but max mass 1.0

Haully
like habitat does
basic, big parts has more volume to LS

Gordon Dry
+ plus some assuming, kinda reference values of RL antennas - put these values in a table and the code finds proper values +/- something

Haully
We need finds a formula that applies in general
like CommNet and RT
I'm playing with both

Gordon Dry
Perhaps not the surface, but the height x width (2-Dimensional)
So it fits long antennas and dishes

Haully
I think that I can't get the width
let me check
I can get the whole area
let me confirm

Gordon Dry
The type must be taken into account - omni only the length, dish the surface (assume a square x * y and calculate how much surface a dish would have, so a circle with some dish shape)

Haully
yep, we can get the x, y and z
form a part

Gordon Dry
and the mass to some intend ...

Haully
Ok, could you open request with all those ideas

Gordon Dry
Well ... yes

Haully
I'm not good to organize those ideas

```

**Comment by SirMortimer** [comment]
There's now API that other mods can implement to affect communication and data rates for Kerbalism. If something like that was to be done, I don't see it happening within the scope of Kerbalism.

**Comment by steamp0rt** [comment]
why
