### ISSUE TITLE
Avoid NEOS experiment results being taken by Kerbalism science hard drive

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#248]
Kinda blacklist it.

See
https://forum.kerbalspaceprogram.com/index.php?/topic/149298-14x-15x-nehemia-engineering-orbital-science-neos-080/&do=findComment&comment=3473514

Quote:

> I've got a pretty good idea of what's going on based on Kerbalism's abstract. It appears to gather all science data into its own module, which, of course, will break NEOS experiments, since the special thing about them is that the science must stay attached to the experiment part in order to be returned to Kerbin for the contracts. So I guess we'll have to try to get Kerbalism to exempt (some of) the NEOS experiments from this behaviour. Or change the way NEOS contracts work with Kerbalism installed.

**Comment by mwerle** [comment]
I just raised the same in issue #249 with some more detail and save games attached.  If Kerbalism has a way to blacklist experiments, that would be ideal.

**Comment by Gordon-Dry** [comment]
Okay.
