### ISSUE TITLE
Suggestion: Add short beep warning sound when signal strenght is below 5%

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#254]
Especially for a Kerbal on EVA this could be an immersion factor.

This sound should not be annoying, so short and nice.
It should repeat every 20 seconds or so as long as the signal strenght is below 5%.

This signal strength <5% could also trigger a little stress level increase for the Kerbal on EVA then ...

In the settings menu it should be possible to set up if only Kerbals or also vessels should have this feature enabled or not.

**Comment by HaullyGames** [comment]
I was testing this idea with 20 vessels, when you have like 5 or 10 vessels below 5%, it start be a mess.

My suggestion, below 5% the signal icon start flashing between yellow and red?

**Comment by Gordon-Dry** [comment]
Okay. Make it annoying at 0.01% then *duck*

**Comment by HaullyGames** [comment]
The point is not the %, but how many vessels are triggering the sound.

**Comment by Gordon-Dry** [comment]
I guess only one warning should be played. Not x warnings simultanously because of x vessels ...

**Comment by HaullyGames** [comment]
https://github.com/ScienceFun/Kerbalism/commit/8164d7ba03982faed02c47a15dbe8f81d24ffd8b

**Comment by steamp0rt** [comment]
no beep, but done.
