### ISSUE TITLE
Autotranslation issue on upgradable parts

### ISSUE THREAD

**Issue by MaximeBrean** [steamp0rt/Kerbalism#260]
I have few translation issue for some part's modules description in VAB/SPH.
Only part that may be upgraded through tech tree are concerned (manned part, ISRU-like and configurable tanks from what I've checked).

Below screenshot illustrating the issue:
![configurable life support](https://user-images.githubusercontent.com/17298958/47593261-eff55080-d976-11e8-84b6-ba2c4e89d537.png)![configurable pod](https://user-images.githubusercontent.com/17298958/47593262-f1bf1400-d976-11e8-922f-f76c22b1cd35.png)![configurable pressurized tank](https://user-images.githubusercontent.com/17298958/47593263-f2f04100-d976-11e8-816a-44e0865ac727.png)

Mod list and versions:
```
KSP: 1.5.1 (Win64) - Unity: 2017.1.3p1 - OS: Windows 7 Service Pack 1 (6.1.7601) 64bit
Kopernicus - 1.5.1.1
BetterTimeWarpContinued - 2.3.10.2
ClickThroughBlocker - 0.1.6.9
Community Category Kit - 4.0
Community Resource Pack - 1.0
Community Trait Icons - 1.0.1
CommunityTechTree - 3.3.3
DistantObjectEnhancement - 1.9.1
DockRotate - 1.4.4.16
Kerbal Engineer Redux - 1.1.5.4
Kerbalism - 2.0
Kerbin Environmental Institute - 1.1.2.3
KSP-AVC Plugin - 1.2.0.6
MechJebForAll - 1.3.0.4
ModularFlightIntegrator - 1.2.5
PartCommanderContinued - 1.1.5.1
SCANsat - 1.1.8.8
ScienceAlert - 1.9.4.3
Stock Visual Terrain - 2.1.4.1
ToolbarControl - 0.1.6.18
Tracking Station Evolved - 1.0.3
```

**Comment by steamp0rt** [comment]
fixed in 3.0
