### ISSUE TITLE
Bug: vessel full of WasteAtmosphere and MoistAtmosphere on launchpad

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#271]
Written to the log several times:
```
ArgumentNullException: Argument cannot be null.
Parameter name: key
  at System.Collections.Generic.Dictionary`2[System.String,KERBALISM.Lib+Module_prefab_data].TryGetValue (System.String key, KERBALISM.Module_prefab_data& value) [0x00000] in <filename unknown>:0 
  at KERBALISM.Lib.ModulePrefab (System.Collections.Generic.List`1 module_prefabs, System.String module_name, System.Collections.Generic.Dictionary`2 PD) [0x00000] in <filename unknown>:0 
  at KERBALISM.Computer.Boot (.Vessel v) [0x00000] in <filename unknown>:0 
  at KERBALISM.Computer.Automate (.Vessel v, KERBALISM.Vessel_info vi, KERBALISM.Vessel_resources resources) [0x00000] in <filename unknown>:0 
  at KERBALISM.Kerbalism.FixedUpdate () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
```

Idea, what could be the reason:
One of the Kerbals inside the vessel is already > 50 radiation poisoned (I turned on life time radiation).
Could it be that this somehow triggers that the vessel is full of "bad resources" when loaded on the launch pad?

**Comment by Gordon-Dry** [comment]
You can see in the craft file that it already is full of WasteAtmosphere and MoistAtmosphere from scratch ...
That means it left the VAB like that ...

Full log and stuff:
https://www.dropbox.com/s/mr139xjpkn2u8c6/2018-10-31_1%20KSP.log%20and%20stuff.7z?dl=1

The last mods I added were:
Cacteye optics (some weird logging about asteroids)
https://forum.kerbalspaceprogram.com/index.php?/topic/141280-151-cacteye-optics-community-takeover/&

FieldTrainingFacility (from Training Kerbalnauts)
https://forum.kerbalspaceprogram.com/index.php?/topic/149796-151-training-kerbalnauts-training-laboratory-field-training-facility/

^that one adds a module to one of the crewed parts I use in my vessel:
```
		MODULE
		{
			name = FieldTrainingFacilityModule
			ECFactor = 1.33333333
			TimeFactor = 9201600
			SpaceFactor = 4
			LandedFactor = 6
		}
```

**Comment by Gordon-Dry** [comment]
I try it again after removing Cacteye and editing the craft file to have 0 amount of the bad resources.
I will load it into VAB and build it again - let's see what happens.

**Comment by MaximeBrean** [comment]
I noticed the following behavior while in VAB/SPH:

- Pop any part that have a Habitat module (let's use MK1 pod as an example). The part have EC/Food/Water/Oxygen/Atmosphere/Nitrogen at full level. WasteAtmosphere and MoistAtmosphere at 0.
- Stop the Habitat module. The Atmosphere go to 0. WasteAtmosphere and MoistAtmosphere stay at 0.
- Start the Habitat module. The Atmosphere, WasteAtmosphere and MoistAtmosphere go full.

No exception raised in log while trying the above.
A new part with Habitat module can be added, WasteAtmo and MoistAtmo are at 0. Above step to the new part will lead to same behavior.

KSP 1.5.1 + Kerbalism 2.0.0.0

**Comment by Gordon-Dry** [comment]
Oh well, okay "that makes sense" ...

**Comment by madman2003** [comment]
https://github.com/steamp0rt/Kerbalism/blob/master/src/Kerbalism/Modules/Habitat.cs#L248
this is the cause in case someone is doing a round of fixes

**Comment by PiezPiedPy** [comment]
@madman2003 👍 and @HaullyGames method needs to set the amount to a default value when in the editor to a stored default rather than max capacity. Also maybe the `if (Lib.IsFlight())` statement should check that it is not in the editor rather than only in flight. 🤷‍♂️

**Comment by madman2003** [comment]
@Gordon-Dry can you confirm this is fixed?

**Comment by Gordon-Dry** [comment]
Yes

**Comment by madman2003** [comment]
@steamp0rt can you close this?

**Comment by Gordon-Dry** [comment]
Well, yep
