### ISSUE TITLE
Signal loss during GameScene changes and SaveGame load

### ISSUE THREAD

**Issue by PiezPiedPy** [steamp0rt/Kerbalism#29]
When changing GameScene's or loading a Save, Signals show as unconnected and then re-connect.

**Comment by PiezPiedPy** [comment]
Maybe found the problem, seems to be due to Kerbalism.cs FixedUpdate method being executed before KSP has finished loading a scene.

I'll start to sort this out once PR's #25 and #30 have been merged.

**Comment by Gordon-Dry** [comment]
Using the private build from PiezPiedBy this issue still occurs.

**Comment by PiezPiedPy** [comment]
probably because I've not added any changes to fix it yet 😛

**Comment by PiezPiedPy** [comment]
Fixed
