### ISSUE TITLE
Transmitting data doesn't cost electric charge?

### ISSUE THREAD

**Issue by squidgeny** [steamp0rt/Kerbalism#294]
I notice from the documentation (https://kerbalism.readthedocs.io/en/latest/signal.html) that "Transmitting data consumes ElectricCharge. The cost is fixed and doesn’t change with distance or signal strength."

However, on starting a new career playthrough with this mod and RemoteTech, I transmitted a crew report (128Mb, I believe) and the electric charge of my Mk1 module didn't drop a single unit.

The documentation doesn't mention it but what *is* the fixed cost being used here? Or is RemoteTech interfering?

I feel like this neuters quite a lot of the challenge, so if there's a way to change it back to "stock" EC useage that would be nice.

**Comment by PiezPiedPy** [comment]
That page is from the days before Stock CommNet was available and Kerbalism had its own signal system, Kerbalism now uses CommNet or RemoteTech. Some of the information on that page is now obsolete.

EC and data rates for antennas are defined in the parts themselves and most are usually representative of real world antennas. Note that 1 EC is equivalent to 1kW, to put things into perspective the Voyager Satellite only uses approx. 20Watt or 0.02 EC for Tx

You can see the EC and data rates an antenna uses in the TechTree or VAB/SPH Parts Info Panels, any antennas fitted to a vessel being built in the VAB/SPH can have their combined rates viewed in the planner by hovering over the EC section.

**Comment by PiezPiedPy** [comment]
looks like I already updated the docs page after Kerbalisms old signals was removed but it was at a time when EC and data rates where a fixed value, looks like it needs updating again.

**Comment by SirMortimer** [comment]
I think this can be closed?
