### ISSUE TITLE
Radial Tanks and Inline Containers not showing up by default.

### ISSUE THREAD

**Issue by dxeh** [steamp0rt/Kerbalism#303]
Hi, 
Kerbalism Radial Tank and Inline Containers seem to be deactivated by default.
Is there a reason for this?

Code says "Category = none" 
Shouldn't that be "Category = Utility" by any change?

Cheers

**Comment by PiezPiedPy** [comment]
Needs closing. Fixed with PR #304

**Comment by PiezPiedPy** [comment]
oy!
