### ISSUE TITLE
VAB Symmetry Issue 

### ISSUE THREAD

**Issue by shaman327** [steamp0rt/Kerbalism#307]
**Version and Mod Info**
- KSP 1.6.1.2401 x64
- Module Manager 3.1.3
- Kerbalism 2.1.1
--Updates to parts config from fix #304 applied so parts will show up.
Community Resource Pack 1.0.0.0 *required by NFE

**Method to reproduce:**
(Included save game test 2 with Testing aircraft and KSP.log file)
1. Load saved game test 2 or create new game with above mods and settings
2. Go into VAB and load 'Test Craft Alpha' or create a simple rocket
3. Select radial container with single symmetry and place on craft. - This should work.
4. Repeat step 3 with double - This should also work
5. Repeat step 3 with triple or more symmetry - This will fail.

**Test Environment Saved Game**
[test 2.zip](https://github.com/steamp0rt/Kerbalism/files/2757905/test.2.zip)

**Test Environment KSP.log**
[KSP.log](https://github.com/steamp0rt/Kerbalism/files/2757899/KSP.log)

**Comment by SirMortimer** [comment]
Fixed in 3.0

**Comment by steamp0rt** [comment]
fixed in 3.0
