### ISSUE TITLE
DMagic Orbital Science's "multi-sample" experiments are locked after one use

### ISSUE THREAD

**Issue by the-emerald** [steamp0rt/Kerbalism#317]
See title. DM Orbital Science adds a few parts that can only be used a certain number of times before they're locked (Solar Particle Collector, Science-9000 mini, etc.). Kerbalism appears to break them and make them single-use only. I've isolated it to Kerbalism causing the issue.

To reproduce: install DM Orbital Science + Kerbalism. Perform an experiment using any multi-sample instrument. It will only allow 1 collection before it is disabled.

**Comment by SirMortimer** [comment]
3.0 will allow for multiple experiments, also on goo. this can be closed.

**Comment by steamp0rt** [comment]
non-issue after 3.0
