### ISSUE TITLE
Where the configure part button has gone?

### ISSUE THREAD

**Issue by JotaRata** [steamp0rt/Kerbalism#321]
Hello I've recently installed Kerbalism and played a new carreer game, I noticed when you are in the SPH or VAB you can't configure vessels or supply containers anymore, I attach a picture of what i'm saying:

_Notice that there is no configure button, and food, water and oxygen resources read zero_

![image](https://user-images.githubusercontent.com/36273501/53059726-a89b4e80-3496-11e9-81a0-7fcc5e2d4a07.png)

**I have installed:**
KSP 1.4.2
Kerbalism 2.1.2
CommunityResourcePack 0.10.0
Module Manager 4.0.1

I hope this is not a bug and there will be an easy solution for this
Thanks for your time

**Comment by steamp0rt** [comment]
Post KSP.log

**Comment by PiezPiedPy** [comment]
try MM 4.02 😉

**Comment by JotaRata** [comment]
> 
> 
> Post KSP.log

KSP Log does not say anything, i'm sorry


> 
> 
> try MM 4.02 😉

I'll try it thanks for the reply

**Comment by steamp0rt** [comment]
yeah MM 4.0.1 is broken

**Comment by JotaRata** [comment]
I downloaded MM 4.0.2 and it did it.
Thanks for your replies:)
