### ISSUE TITLE
Space Station Parts Redux "Aquaculture" experiment broken

### ISSUE THREAD

**Issue by the-emerald** [steamp0rt/Kerbalism#324]
It still shows a 0.3(?)x xmit scalar, and the experiments doesn't show up in the Kerbalism section (it shows up in the command pod). Not sure how SSPX is able to override the science system that Kerbalism has.

**Comment by UsernamesAreAlwaysTaken** [comment]
This will be fixed with the new science system.

**Comment by steamp0rt** [comment]
fixed in 3.0
