### ISSUE TITLE
resource error, ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by peq123** [steamp0rt/Kerbalism#328]
hi there, i have encoutered a bug when trying to symmetrically place a part with a kerbalism resource. I have tested this with several parts such as the "pressurised tanks" with each being able 2x placement but any higher causes a spam of the log with the following error:

[EXC 09:13:37.750] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
    System.Collections.Generic.List`1[PartResource].get_Item (Int32 index)
    DictionaryValueList`2[System.Int32,PartResource].At (Int32 index)
    PartResourceList.get_Item (Int32 index)
    Part.OnCopy (.Part original, Boolean asSymCounterpart)
    EditorLogic.createSymmetry (Int32 mode, .Attachment attach)
    EditorLogic.<SetupFSM>m__D ()
    KerbalFSM.UpdateFSM ()
    EditorLogic.Update ()

found this issue in my career mode then removed all mods apart from below to test in sandbox on ksp 1.6.1 with 

kerbalism                               2.1.2

module manager                 4.02

community resource pack 1.1.0.0

 

hope this helps to resolve this

 

thanks

**Comment by peq123** [comment]
https://forum.kerbalspaceprogram.com/index.php?/topic/172400-literally-every-ksp-version-since-13-kerbalism-v212/&do=findComment&comment=3548119

**Comment by PiezPiedPy** [comment]
I've noticed this too but I've not looked into the cause yet

**Comment by GuiltyNeko** [comment]
I've had the same issue, which I've been able to temporarily fix on each occasion by cycling through every variation in the kerbalism module switcher. Doesn't always work, but usually does.

**Comment by SirMortimer** [comment]
This was duplicated by #375 - see there.
