### ISSUE TITLE
Fuel Cell only works manually

### ISSUE THREAD

**Issue by mekaerwin** [steamp0rt/Kerbalism#329]
When I set the fuel cell to come on at 20% or off at 80% clicking on it says running or off appropriately but it is not actually changing. Manually switching it works. Turning it on or off in device manager under devices also does not work.
I simply take a command pod and add hydrogen tank to side and fuel cell. Launch mission and set up as above. I have no mods other than Kerbalism and Community Resource pack and ran without the expansion installed. I am using ModManager 4.0.2. I have tested on both launch pad and in flight.

I can submit a save but it is simply sandbox start.
I'm not sure if there is anything else you would like.

-Edit
I'm running the latest version 1.6.1

**Comment by SirMortimer** [comment]
can confirm. working on a fix.
