### ISSUE TITLE
Add upgrades by adding a Kerbalism slot with PartUpgrade

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#33]
Referring to https://forum.kerbalspaceprogram.com/index.php?/topic/172400-131143-kerbalism-v160/&do=findComment&comment=3388591

Make it possible to have one additional Kerbalism slot as soon a specific tech tree node like Miniaturization or even heavyCommandModules (for crewed pods) is researched for the following parts:

- kerbalism-chemicalplant
- MiniISRU
- ISRU
- smallISRU
- crewed pods

The tech tree node when it happens could depend of the type of part.

**Comment by PiezPiedPy** [comment]
Managed to get this to work but I feel Miniaturization is too early in the TechTree so I have chosen to use the Electronics tech instead.

**Comment by PiezPiedPy** [comment]
Also noticed that the Chemical Plant was not having its capacity correctly set due to its .cfg file rename, so fixed that small issue too.

**Comment by PiezPiedPy** [comment]
Seems I spoke too soon 😠 After the upgrade is purchased and gets applied by KSP, the titles of the info tabs disappear.
![missing titles](https://user-images.githubusercontent.com/17555434/40688473-2010722e-6396-11e8-8321-97f094d21298.png)

**Comment by PiezPiedPy** [comment]
Fixed the titles not showing correctly, problem was caused by KSP using a new method `GetModuleDisplayName` when the upgrades are applied to get the titles rather than the original `GetModuleTitle`

**Comment by PiezPiedPy** [comment]
For some reason after the upgrade is purchased the Tooltip widgets no longer display alphabetically, result being that the Configure tooltip is no longer displayed at the top of the Tooltip.
Not much of a problem and can be lived with (I suppose we don't have a choice lol, until Squad fix the issue).
