### ISSUE TITLE
Not sure if this is a bug: "Exception: psuedo-resource _HyLiquefaction must be NO_FLOW"

### ISSUE THREAD

**Issue by scott4dges** [steamp0rt/Kerbalism#333]
Kerbalism version: 2.1.2
KSP version: 1.6.1
Module Manager DLL: 4.0.2

Sorry, I don't really use GitHub but thought you might want this in here vs. just having it on the Kerbalism KSP forum thread. Please let me know if you need other information or if this isn't the right place to put this info.

#################
Exception code that is spamming in my latest log:
`[EXC 11:08:08.378] Exception: psuedo-resource _HyLiquefaction must be NO_FLOW﻿
	KERBALISM.Modifiers.Evaluate (.Vessel v, KERBALISM.Vessel_info vi, KERBALISM.Vessel_resources resources, System.Collections.Generic.List 1 modifiers, .Part p, .ProtoPartSnapshot pp)
	KERBALISM.Process.ExecuteVesselWide (.Vessel v, KERBALISM.Vessel_info vi, KERBALISM.Vessel_resources resources, Double elapsed_s)
	KERBALISM.Process.Execute (.Vessel v, KERBALISM.Vessel_info vi, KERBALISM.Vessel_resources resources, Double elapsed_s)
	KERBALISM.Profile.Execute (.Vessel v, KERBALISM.Vessel_info vi, KERBALISM.VesselData vd, KERBALISM.Vessel_resources resources, Double elapsed_s)
	KERBALISM.Kerbalism.FixedUpdate ()
[ERR 11:08:08.394] Resource System Error: Requested resource (id: 1203312488) does not exist﻿`

#################
Here's the full log for reference: [KSP 031219 Time 1111.log](https://www.dropbox.com/s/mcv2fck6zit5j4m/KSP%20031219%20Time%201111.log?dl=0)

**Comment by scott4dges** [comment]
Looking more closely at my latest log, I only see two places where "HyLiquefaction" is listed:

[LOG 16:41:45.847] Config(RESOURCE_DEFINITION:NEEDS[CryoTanks,Kerbalism,ProfileDefault]) Kerbalism/Support/CryoTanks/_HyLiquefaction
[LOG 16:41:45.854] Config(RESOURCE_DEFINITION:NEEDS[FTT,Kerbalism,ProfileDefault]) Kerbalism/Support/USI/USI_FTT/_HyLiquefaction
I've checked both those files in the file location, and they do list parameters for "HyLiquefaction" but I don't see anything related to "NO_FLOW" or anything. Unfortunately, this is where my code understanding stops.

Note that I don't have USI or any other Life Support mods installed.

**Comment by PiezPiedPy** [comment]
I have an idea what it is but I could be wrong, I'll have a look in a few days, I'm tied up at the moment.

**Comment by PiezPiedPy** [comment]
try adding `	flowMode = NO_FLOW` to the definitions in those two files.

e.g.
```RESOURCE_DEFINITION:NEEDS[FTT,Kerbalism,ProfileDefault]
{
	name = _HyLiquefaction
	density = 0.0
	isVisible = false
	flowMode = NO_FLOW
}
```

Note that this is only a temp workaround (if it works), the problem is actually in the simulator.
