### ISSUE TITLE
Make background processing of Kerbalism recognize StoredCharge "helping out" when lack of EC (RealBattery)

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#34]
A crewed pod with not so much EC but way enough SC (StoredCharge) provided by RealBattery alerted me about lack of EC (Kerbin dark side) and CO2 poisoning.

The thing is, in focus and as well with a non-Kerbalism install, the background processing always works well.

As soon as the EC decreases below a set amount (RealBattery default 80%), SC is converted to EC.
As soon as EC comes back in (solar panels for example), the "normal" batteries are charged to (default) 90%, then the SC is charged to 100%, then the EC is charged to 100%.

1 SC is equivalent to 3600 EC, so a small amount of SC is fair enough.

In my install I changed the RealBattery values from 0.8/0.9 to 0.2/0.8 and it works well - normally.

But with Kerbalism a crewed mission is in danger if there is not enough "normal" EC - the SC part actually is useless.

So I request that the input of SC-converted-to-EC is recognized by Kerbalism.

For now I set the lower value of RealBattery to 0.3 - I will see the outcome after rebooting KSP.

**Comment by Gordon-Dry** [comment]
So, the level didn't change anything, the batteries are just going down to 0 - so there is definetely no background proecessing of RealBattery possible when Kerbalism is in charge.

**Comment by Gordon-Dry** [comment]
Could it perhaps be that this is the culprit?
GameData\Kerbalism\Support\Kopernicus.cfg
```
// Why we are disabling the Kopernicus custom module implementing their multi-star fix:
// - we can't leverage it for background simulation
// - warp fixer de-facto replace their computations anyway
// - a lot of our code assume a single star, multiple stars support is planned for a future release
// - lack of time to further investigate the interactions

@PART:HAS[@MODULE[ModuleDeployableSolarPanel]]:NEEDS[Kopernicus]
{
  @MODULE[ModuleDeployableSolarPanel]
  {
    %useKopernicusSolarPanels = false
  }
}
```
What happens when I set it to true?

**Comment by steamp0rt** [comment]
Why would that be related?

**Comment by steamp0rt** [comment]
Kerbalism just simply doesn't take RealBattery into account

**Comment by Gordon-Dry** [comment]
Okay ...

So another vessel destroyed and crew killed because the parachute didn't deploy ...

As soon as a message occurs because of low EC (happens in high timewarp when not in flight mode) and timewarp stops and immediately after that the message pops up that EC is restored ... something happens that makes the parachutes not deploy later.

No exceptions in the log.

But here it is:
https://www.dropbox.com/s/wiuqtxayd3680om/2018-05-31_1%20KSP.log.7z?dl=1

**Comment by Gordon-Dry** [comment]
I close this for now because actually I use the private build from PiezPiedBy and I can't confirm if this is really a Kerbalism issue - but it's very new in its occurance ...
