### ISSUE TITLE
Command Pod unlockable ECLSS displays as "#autoloc_12345...." in KSP 1.6.1

### ISSUE THREAD

**Issue by TicTac-93** [steamp0rt/Kerbalism#360]
Thanks to forum user kerbalspeed for this image: ![ECLSS Error](https://user-images.githubusercontent.com/30486030/54999064-dd268c80-4fa5-11e9-8e9d-e1118891e284.jpg)

I've checked this on a clean installation of 1.6.1, with no mods but Kerbalism and its dependencies installed via CKAN.  It should be reproduceable that way.  The issue does not occur with the latest release of Kerbalism on my 1.4.5 installation.  AFAIK it does not affect functionality at all, but I haven't rigorously tested that.

**Comment by SirMortimer** [comment]
It was introduced with KSP 1.6 I think. The translation is done by KSP itself, and the way that works seems to have changed slightly. I've already fixed that for the next version.

**Comment by TicTac-93** [comment]
Great, I'll close this
