### ISSUE TITLE
Food amount updates rarely (using repo "Changes to support Slot upgrades (#36)")

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#37]
I just recognized after nearly 3 hours in orbit all food is still 100%.
Oxygen and water are used.

After clicking around and opening and closing some GUI from other mods, the percentages of 6 Universal Storage Food Bags suddenly jumped down to 98% and also the Kerbalism UI readout jumped down from 30d 1h to 29d 4h.

It's like the readout for food is updated very rarely.

No exceptions in the log.

**Comment by PiezPiedPy** [comment]
How did you build the dll ?

**Comment by Gordon-Dry** [comment]
Well, I didn't, I downloaded the latest repo from 3 hours ago.

**Comment by Gordon-Dry** [comment]
Oh, well, the repo had all changed configs in it, but still the dll from 4 days ago ...
Darn.

**Comment by PiezPiedPy** [comment]
maybe, there have been hundreds of changes to the code in the last couple of PR's
Try my build ;)
[Kerbalism-v1.6.1_For_KSP1.4.3.zip](https://github.com/steamp0rt/Kerbalism/files/2056223/Kerbalism-v1.6.1_For_KSP1.4.3.zip)

**Comment by Gordon-Dry** [comment]
Thanks - I was just typing that I wanted to retry the reentry with a backup savegame using the latest RLS, then your post popped in ...

**Comment by Gordon-Dry** [comment]
Using your build the food amount (time left) still updates rarely.

**Comment by PiezPiedPy** [comment]
I'll look into it

**Comment by PiezPiedPy** [comment]
Food only updates twice a day, which is when Kerbal's eat a meal

**Comment by Gordon-Dry** [comment]
This could be mentioned in the README or the wiki perhaps to avoid confusion.

**Comment by PiezPiedPy** [comment]
good idea, I will leave you too it 😉

**Comment by Gordon-Dry** [comment]
Closing.
