### ISSUE TITLE
After the latest update my KSP won't load

### ISSUE THREAD

**Issue by bartekkru100** [steamp0rt/Kerbalism#378]
After updating to Kerbalism 2.2.0 the game at some point stops loading and is stuck at one specific part
![image](https://user-images.githubusercontent.com/9304355/55749222-b144e580-5a40-11e9-832c-4bf0333c2c94.png)
I use module manager 4.0.2.

**Comment by Rockstar04** [comment]
2.2.0 was published in error, and contains work in progress changes to the science system. I would suggest you downgrade to 2.1.2 for now.

**Comment by steamp0rt** [comment]
What @Rockstar04 said
