### ISSUE TITLE
incompatibility issue with new ksp 1.7

### ISSUE THREAD

**Issue by tonimark** [steamp0rt/Kerbalism#385]
the new versions 1.7 is incompatible with herbalism 2.1.2 the issue is that the kerbalism and life support don't load among the deletions of modules such as (scrubber...)its like the mod is not installed. the issue is referred to an SSPX compatibility patch file discovered by Tonas1997 (an issue also inverts inflatable and deflatable crew capacity status in inflatable habitats) for more information check:https://forum.kerbalspaceprogram.com/index.php?/topic/172400-literally-every-ksp-version-since-14-kerbalism-v212/&page=64&tab=comments#comment-3592706
logs(initializing only):
[KSP.log](https://github.com/steamp0rt/Kerbalism/files/3144561/KSP.log)
[debug.log](https://github.com/steamp0rt/Kerbalism/files/3144562/debug.log)

**Comment by SirMortimer** [comment]
1. Rename Kerbalism16.bin to Kerbalism17.bin
2. Rename Shaders/16 to Shaders/17

or

3. Test Kerbalism 3.0

**Comment by SirMortimer** [comment]
The inflatable habitat works correctly on my install, and AFAIK those config files have not been touched since 1.2.1. 

@steamp0rt this can be closed.

**Comment by tonimark** [comment]
ok lets check
