### ISSUE TITLE
Supply containers need balancing.

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#52]
By default their contents should be balanced.
Not to a scenario with converting / water processing / greenhousing.
Just the containers themselves.

For example, when I add a container I have way more water than food.
If I need additional water, I could use another tank with it.

**Comment by PiezPiedPy** [comment]
I've got this on my list of thing to do,
Idea is to get the volume of the containers and use a resources density to arrive at an amount.

**Comment by leomike** [comment]
I believe this was resolved by #148.

**Comment by PiezPiedPy** [comment]
Needs closing, was sorted a while back
