### ISSUE TITLE
Water is increasing with humidity controller

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#66]
Okay, Kerbals drink water and they sweat water and they breath-out water.

Is the module also recycling pee?

But if yes or no, it doesn't matter; the total amount of water available in the vessel cannot increase as long no processing of Hydrogen/Oxygen is taken into account.

So I guess the humidity thing needs to be nerfed again... ;)

**Comment by PiezPiedPy** [comment]
amount of water breathed out is 850ml / day , the rates are correct. I spent a lot of time checking.
850ml is 0.85 units of water.
850mL divided by density of Water = 0.85L, divided by 21600 seconds (a Kerbal day of 6hrs) = 0.0000393519/sec or 0.002361114/min or 0.14166684/hr
Note that saved craft (even craft loaded into the editor) will have values from previous versions.
Have  you tried a newly built vessel.

**Comment by PiezPiedPy** [comment]
the water recycler processes the kerbal's waste water (pee) which is not 100% of the water they drink

**Comment by Gordon-Dry** [comment]
Yes, the pod and shield are new because I also still fiddle with my heatshield patch thing.

It was that after launch it got food and water for 15d (1 Kerbal in a Gemini pod plus extra supplies in a service bay) and Oxygen for 28d.
In orbit for about one hour the water readout increased up to 23d.

**Comment by PiezPiedPy** [comment]
the humidity controller will only kick in when you leave the atmosphere, thus the increase in duration of water when in orbit.

**Comment by PiezPiedPy** [comment]
check the water duration in the planner by turning the humidity controller on/off and observe the change in duration of water

**Comment by Gordon-Dry** [comment]
Ok, I believe you ;-)

**Comment by PiezPiedPy** [comment]
I'm curious to know now, does the increase in duration in the planner match the duration in orbit ?
