### ISSUE TITLE
Request: config settings available without signal when pod is crewed

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#71]
A crewed command pod should give the player  access to the configs whatsoever, not only when a Commnet connection is established.

**Comment by PiezPiedPy** [comment]
I assume you mean when a Kerbal is inside the pod ?

**Comment by Gordon-Dry** [comment]
Yes.

For the immersion, when the Kerbal goes EVA, you switch to the pod (assume it's empty now), you 
cannot change the config anymore when no Commnet link established ...
Do you mean that?

Would be cool. Could confuse ppl. But a wiki could help. A readme entry as well. ;-)

**Comment by PiezPiedPy** [comment]
Fixed with PR #76

**Comment by Gordon-Dry** [comment]
Ok
