### ISSUE TITLE
Request: support Xenon (Argon) ion engines and RCS thruster in planner

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#73]
BDB:
bluedog_ERCS*
bluedog_Tempel2_Ion

NearFutureElectrical:
ionXenon-0625*
vasimr*
rcsblock-gridded-01

NSS:
OctoSat_Pr_Ion

Squad:
ionEngine

SSTL:
sstl-300S1

afaik

**Comment by Gordon-Dry** [comment]
For the bluedog_ERCS* and bluedog_Tempel2_Ion and others with the same method as well, you could check for:

ModuleRCSFX (ModuleRCS)
ModuleEnginesFX (ModuleEngines)

which have XenonGas / ArgonGas / Hydrogen and also ElectricCharge as additional propellant.

If they have, they should be recognized by the planner.

**Comment by Gordon-Dry** [comment]
Perhaps only a check for ElectricCharge as additional propellant is enough ...

**Comment by PiezPiedPy** [comment]
See PR #86
