### ISSUE TITLE
Add tags to parts for easy find

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#75]
Like to the external ECLSS add tags
pressure humidity fuel cell fuelcell scrubber waste water processor recycler

Just like that.

**Comment by PiezPiedPy** [comment]
tags are already added? parts are in the Kerbalism parts tab
![screenshot0](https://user-images.githubusercontent.com/17555434/41820802-2d7ff8ba-77cf-11e8-9ce6-2be414a7917f.png)

**Comment by Gordon-Dry** [comment]
I mean when just entering a search word in the search field, like "humidity", to get quick access to according parts.

**Comment by PiezPiedPy** [comment]
ahhh I see

**Comment by Gordon-Dry** [comment]
Closed with
https://github.com/steamp0rt/Kerbalism/pull/82/commits/ef0153bee528f7f9af84816ce3a4fdc0f360980e
and
https://github.com/steamp0rt/Kerbalism/pull/82/commits/ae6964200c7e75954277881a476299a9ed6fa00f
