### ISSUE TITLE
Request: add max. thrust reduction of EC consuming engines like ion propulsion to EC auto

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#85]
A request for a later enhancement.

Example:
An early gen probe with ion propulsion engines but only solar panels, no reactor.
Low EC (20%) is reached, because the solar panels don't provide enough EC anymore because a vessel is far away from sun.
Reduce the max. thrust of ion propulsion engines in a matter that the vessel's EC consumption is lower than its EC production - at best to be balanced out.

**Comment by Gordon-Dry** [comment]
This is especially a request because when a maneuver burn is going on it'S impossible to reduce the thrust.
ofc the engine's PAW provides a slider, but an automation is better.

Especially when the probe is even going more far away from sun and the thrust has to be reduced step by step on a long duration burn...

**Comment by lordcirth** [comment]
Why is it impossible to reduce the thrust?  Why not throttle down?  Also, it's common in KSP to fire ion engines in bursts and wait for the battery to recharge, for example one burn per orbit.  Limiting thrust to only what can be sustained indefinitely would interfere with this approach.

**Comment by Gordon-Dry** [comment]
During a maneuver burn you cannot just throttle down.
But okay, everybody has another approch.

How about a long burn on interplanetary trajectory?
Perhaps even a really long one, you go to the grocery store meanwhile ;)

**Comment by steamp0rt** [comment]
not within the scope of kerbalism
